name: Lint,test and deploy
on: push
jobs:
    setup:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: npm ci
              run: npm ci
    lint:
        needs: setup
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: setup lint
              run: npm install eslint --save-dev
            - name: Run lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Run tests
              run: npm test
            - name: build npm
              run: npm run build

